source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'Playground'
use_frameworks!

def common_pods
    # Since this library depends on 'prepare_command' for compiling SwiftGen
    # and other automations, we need to install it as a remote pod.
    
    # remote
    pod 'Iconic', :git => 'https://github.com/dzenbot/Iconic.git', :submodules => true
    
    # local
#    pod 'Iconic', :path => '/Users/iromero/Desktop/DZN/OSS/Iconic/Iconic.podspec', :submodules => true
end

target 'iOS' do
    platform :ios, '8.0'
    common_pods
end

target 'tvOS' do
    platform :tvos, '9.0'
    common_pods
end

target 'UnitTests' do
    # No need for installing the pod.
    # This target tests 'Iconic' main class only.
end

target 'SnapshotTests' do
    common_pods
    pod 'FBSnapshotTestCase/Core'
end