source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'Playground'
use_frameworks!

def common_pods
    pod 'Iconic', :path => '../Iconic.podspec', :submodules => true
end

target 'iOS' do
    platform :ios, '8.0'
    common_pods
end

target 'tvOS' do
    platform :tvos, '9.0'
    common_pods
end

target 'Tests' do
    common_pods
    pod 'FBSnapshotTestCase/Core'
end

# prepare_command doesn't consistently work with local pods
# This might cause double installation in local environment, but at least not fail in CI environment.
pre_install do |installer|
    system("sh ../Installer.sh Fonts/FontAwesome-4.6.3/FontAwesome.otf ../")
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
